# This is a basic workflow to help you get started with Actions

name: Build and Deploy Static Site

on:
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Hello World
        run: echo "hello world!"

      - name: Build HTML using oxr463/setup-leiningen
        uses: oxr463/setup-leiningen@0.0.1
        with:
          exec: lein run

      #- name: Copy the HTML to the public folder
      #  run: mkdir _site

      #- name: Copy the HTML to the public folder
      #  run: cp rendered/* _site

      #- name: Copy the contents of resources/public/ to the public folder
      #  run: cp resources/public _site

      #- uses: actions/upload-pages-artifact

      #- uses: actions/deploy-pages
